### ISSUE TITLE
Button color must be blue

### ISSUE THREAD

**Issue by umutcandev** [xrh0905/flarum-ext-oauth-microsoft#1]
First of all, thank you very much for the plugin.

I think the button should be finished with the blue color we are familiar with from Microsoft, for example like below:
#004578

Thanks in advance for the evaluation.

**Comment by umutcandev** [comment]
Also, the Readme field says Amazon instead of Microsoft. It needs to be fixed too.

**Comment by xrh0905** [comment]
Thanks for advice! I'll fix it.

**Comment by xrh0905** [comment]
Solved!
Thanks again
